AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an EC2 instance with a security group

Resources:
  WebServerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro  
      ImageId: ami-0c55b159cbfafe1f0  
      SecurityGroups:
        - !Ref WebServerSecurityGroup
      KeyName: key-pair 

